# Generated by Django 3.1.5 on 2021-02-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
